### PR TITLE
Extended shouldHide method

### PR DESCRIPTION
**Pull request by bitbeans**
- Added Microsoft-ISATAP

### CODE REVIEW

**Comment by Noxwizard** [comment]
What version of Windows is using this hyphenated name?

**Comment by bitbeans** [comment]
8.1 64 bit

**Comment by Noxwizard** [comment]
I do not see this on my 8.1 x64 machine. Are you using a localized version of Windows? I do see that Microsoft changed the description on the Teredo adapter in 8.1 an 10, which means I should probably switch to checking names and not descriptions. I do not see this change though.

**Comment by bitbeans** [comment]
Yes i use a german version.

**Comment by bitbeans** [comment]
An here is a screenshot on a Windows 10 notebook (x64 german version):
w10

**Comment by bitbeans** [comment]
@Noxwizard status? :)

**Comment by Noxwizard** [comment]
It's very unlikely this will be merged. The root of the problem is caused by the application looking at adapter descriptions, which have the potential to be translated differently in localized versions of Windows. The correct fix would be to find a device identifier (Hardware ID, Device Instance Path, etc.) that is not changed between versions. This PR also has other commits attached with no reasoning as to why, as well as breaking formatting styles.

**Pull request closed without merging**
